name: Makefile CI

on:
  push:
    branches: [main, develop, feature/**, release/**]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
          submodules: recursive

      - name: configure
        run: ./configure

      - name: Install dependencies
        run: make

      - name: Run check
        run: make check

      - name: Run distcheck
        run: make distcheck
