name: Makefile CI

on:
  push:
    branches: [main, develop, feature/**, release/**]
  pull_request:
    branches-ignore: [main, develop, feature/**, release/**]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: make
