name: uBO Release

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_call:

permissions:
  contents: write
  discussions: write

jobs:
  build:
    permissions:
      # for creating release
      contents: write

    runs-on: ubuntu-latest
    name: Build Packages
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
          submodules: recursive

      - name: Clone uAssets
        run: |
          tools/pull-assets.sh

      # https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
      - name: Get release information
        id: release_info
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_STATE

      - name: Assemble release notes
        run: |
          > release.body.txt
          grep -m1 -B10000 -- "----------" CHANGELOG.md >> release.body.txt
          sed -e 's/%version%/${{ steps.release_info.outputs.VERSION }}/g' RELEASE.HEAD.md >> release.body.txt

      - name: Build MV2 packages
        run: |
          tools/make-chromium.sh ${{ steps.release_info.outputs.VERSION }}
          tools/make-firefox.sh ${{ steps.release_info.outputs.VERSION }}
          tools/make-thunderbird.sh ${{ steps.release_info.outputs.VERSION }}
          tools/make-npm.sh ${{ steps.release_info.outputs.VERSION }}

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.release_info.outputs.VERSION }}
          name: ${{ steps.release_info.outputs.VERSION }}
          draft: true
          prerelease: true
          body_path: release.body.txt
          files: |
            dist/build/uBlock0_${{ steps.release_info.outputs.VERSION }}.chromium.zip
            dist/build/uBlock0_${{ steps.release_info.outputs.VERSION }}.firefox.xpi
            dist/build/uBlock0_${{ steps.release_info.outputs.VERSION }}.thunderbird.xpi
            dist/build/uBlock0_${{ steps.release_info.outputs.VERSION }}.npm.tgz
